### ISSUE TITLE
JSDom Error: undefined is not a function

### ISSUE THREAD

**Issue by mwbrooks** [adrianblynch/page-link-checker#1]
Hi @adrianblynch,

I'm just scouting around for a good page link checker and I came across your project. Unfortunately, I'm running into an error with your library.

Using:

`page-link-checker@1.0.3`

Running your example code:

```javascript
var plc = require("page-link-checker")

// Check links on a page
var pageUrl = "https://github.com/adrianblynch?tab=repositories"
plc.check(pageUrl, function (err, responses) {
    console.log("Page URL:", responses)
})
```

I receive the following error:

```bash
$ node test.js
/Users/mwbrooks/Development/lib/phonegap-docs/node_modules/page-link-checker/node_modules/jsdom/lib/jsdom/browser/Window.js:41
  this._document = new dom.HTMLDocument({
                   ^
TypeError: undefined is not a function
```

Cheers,
Michael

**Comment by adrianblynch** [comment]
Hi Michael, thanks for the find. I'm looking into this now. It sounds like it's an issue with the modules I'm relying on. Odd that my tests (extra ones I'm now writing) pass but a stand-alone example fails.

Will keep digging.

**Comment by adrianblynch** [comment]
I've swapped out [jsdom](https://www.npmjs.com/package/jsdom) for [cheerio](https://www.npmjs.com/package/cheerio) which has had led to two benefits: the bug you found has gone away and this now works on Node and io.js without the need to stay using an old version of jsdom.

**Comment by mwbrooks** [comment]
Hi @adrianblynch, thanks a bunch for diving into this issue! Tomorrow, I'll give it a spin and see how it goes!

Cheers,
Michael

**Comment by mwbrooks** [comment]
Hey @adrianblynch,

This works a lot better now! Thanks a bunch for swapping out jsdom.

I've now running into a new issue - which is more of a feature question, so I'll kick up a new issue to change the discussion topics.

Thanks a ton for helping out,
Michael
