### ISSUE TITLE
Absolute URL Requirement

### ISSUE THREAD

**Issue by mwbrooks** [adrianblynch/page-link-checker#2]
This may be a feature or a bug, depending on the scope of the project.

Throughout my project, I use relative URLs to reference pages, such as:

```html
<a href="/path/to/some/page">Some Page</a>
```

However, `page-link-checker` appears to always expect an absolute URL such as:

```html
<a href="example.com/path/to/some/page">Some Page</a>
```

The result is that my relative links all return as broken.

Cheers,
Michael

**Comment by adrianblynch** [comment]
Thanks Michael.

I've published a new version which allows you to specify a base URL.

The method now looks like `check(page[, baseUrl], callback)`.

I would have liked to have tried to derive the base URL from the supplied HTML or link but I feel like that's a bit of a minefield.

Doing this extra work has also highlighted issues with 30x status codes that I need to rep. and issue up also.

Thanks for the feedback and let me know how it works for you.
